const TAG='Onlinestarkei-21';
const products=[
['B01M8G4JVD','Brüder Mannesmann','Werkzeugkoffer M29084, 87-teilig','Koffer','Wohnung','49,99 €','https://m.media-amazon.com/images/I/81JdHjnV9eL._AC_AIweblab1378949,T3_SF516.0,327.0_PQ65_.jpg?aicid=productui-image-1'],
['B084XPQNG2','kwb','Universal-Werkzeugkoffer, 42-teilig','Koffer','Wohnung','35,49 €','https://m.media-amazon.com/images/I/61ijNy57kjL._AC_AIweblab1378949,T3_SF516.0,327.0_PQ65_.jpg?aicid=productui-image-1'],
['B0051E16LW','Brüder Mannesmann','Haushalts-Werkzeugkoffer M29085, 89-teilig','Koffer','Haus','52,84 €','https://m.media-amazon.com/images/I/719CZ7WNJIL._AC_AIweblab1378949,T3_SF516.0,327.0_PQ65_.jpg?aicid=productui-image-1'],
['B07X9YL4JT','Hi-Spec','Werkzeugset Haushalt & Garage, 53-teilig','Koffer','Werkstatt','26,99 €','https://m.media-amazon.com/images/I/81ShRRiSKqL._AC_AIweblab1378949,T3_SF480.0,480.0_PQ65_.jpg?aicid=productui-image-1'],
['B076B5VS85','Brüder Mannesmann','Werkzeugkoffer M29032, 47-teilig','Koffer','Wohnung','33,48 €','https://m.media-amazon.com/images/I/81CgXt3mC9L._AC_AIweblab1378949,T3_SF516.0,327.0_PQ65_.jpg?aicid=productui-image-1'],
['B005ERFK9U','Brüder Mannesmann','Alu-Werkzeugkoffer M29075, 108-teilig','Koffer','Werkstatt','89,56 €','https://m.media-amazon.com/images/I/91a12TvWP+L._AC_AIweblab1378949,T3_SF516.0,327.0_PQ65_.jpg?aicid=productui-image-1'],
['B07ZCV6FJ5','Hi-Spec','Werkzeugkoffer mit Bit-Set, 42-teilig','Koffer','Wohnung','21,99 €','https://m.media-amazon.com/images/I/81QOdEoAt1L._AC_AIweblab1378949,T3_SF516.0,327.0_PQ65_.jpg?aicid=productui-image-1'],
['B0CGDXKS9K','kwb','Universal-Werkzeugkoffer, 35-teilig','Koffer','Wohnung','20,55 €','https://m.media-amazon.com/images/I/71K9ZL4gy5L._AC_AIweblab1378949,T3_SF480.0,480.0_PQ65_.jpg?aicid=productui-image-1'],
['B0DQD6STMP','Hi-Spec','Werkzeugkoffer mit 4V USB-Akkuschrauber','Elektro','Wohnung','29,99 €','https://m.media-amazon.com/images/I/71fKrPlICNL._AC_AIweblab1378949,T3_SF516.0,327.0_PQ65_.jpg?aicid=productui-image-1'],
['B0G396NBSW','Hi-Spec','Werkzeugset mit 3,6V USB-Akkuschrauber','Elektro','Wohnung','29,91 €','https://m.media-amazon.com/images/I/81u4MF4dmPL._AC_AIweblab1378949,T3_SF480.0,480.0_PQ65_.jpg?aicid=productui-image-1'],
['B0CRH89MVB','WMC TOOLS','Kleiner Werkzeugkoffer, 11-teilig','Koffer','Wohnung','14,99 €','https://m.media-amazon.com/images/I/71QDglzH27L._AC_AIweblab1378949,T3_SF516.0,327.0_PQ65_.jpg?aicid=productui-image-1'],
['B0DYVM1YKX','BAMATO','Werkzeugtrolley WORK-193, 193-teilig','Koffer','Werkstatt','173,99 €','https://m.media-amazon.com/images/W/BW_MEDIAX_AVIF_MEASUREMENT_1306696-T1/images/I/81We33VcIaL._AC_SR160,134_CB1169409_QL70_.jpg']
].map(x=>({asin:x[0],brand:x[1],name:x[2],cat:x[3],use:x[4],price:x[5],img:x[6]}));
const topics=[
['werkzeugkoffer-grundausstattung','Der erste Werkzeugkoffer: Was wirklich hineinmuss','Mit 15 gut gewählten Werkzeugen erledigst du die meisten Arbeiten in der Wohnung. Wir zeigen eine belastbare Grundausstattung.','Wohnung'],
['werkstatt-einrichten','Die erste Werkstatt sinnvoll einrichten','Von Licht und Strom bis Werkbank und Aufbewahrung: So wächst eine Werkstatt mit deinen Projekten.','Werkstatt'],
['akkuschrauber-kaufen','Akkuschrauber kaufen: Volt, Drehmoment, Akku','Welche Leistungsdaten zählen – und wann ein kompakter 12-Volt-Schrauber die bessere Wahl ist.','Elektro'],
['bohrmaschine-oder-bohrhammer','Bohrmaschine oder Bohrhammer?','Beton, Ziegel oder Holz verlangen unterschiedliche Maschinen. Diese Entscheidungshilfe verhindert Fehlkäufe.','Elektro'],
['zangen-grundausstattung','Diese drei Zangen reichen für den Start','Kombizange, Wasserpumpenzange und Seitenschneider: Aufgaben, Größen und sichere Anwendung.','Handwerk'],
['schraubendreher-bits','Schraubendreher und Bits richtig auswählen','PH, PZ, Torx oder Schlitz? Profile erkennen, passende Größe wählen und Schrauben schonen.','Handwerk'],
['werkzeug-fuer-mietwohnung','Werkzeug für die erste Mietwohnung','Eine kompakte Auswahl für Möbel, Bilder, Lampen und kleine Reparaturen – ohne unnötigen Ballast.','Wohnung'],
['werkzeug-fuer-haus','Werkzeug-Grundausstattung fürs eigene Haus','Mehr Fläche, mehr Aufgaben: Welche Ergänzungen zu Koffer, Leiter und Maschinen langfristig sinnvoll sind.','Haus'],
['gartenwerkzeug-grundausstattung','Gartenwerkzeug: Die sinnvolle Grundausstattung','Für Beet, Rasen, Hecke und Terrasse: ergonomisch auswählen, pflegen und platzsparend lagern.','Garten'],
['werkbank-planen','Die richtige Werkbank planen','Arbeitshöhe, Spannmöglichkeiten, Licht und Stauraum bestimmen, bevor du kaufst oder baust.','Werkstatt'],
['werkzeug-aufbewahren','Werkzeug übersichtlich aufbewahren','Koffer, Wandtafel, Schublade oder Trolley: Welches System zu welchem Arbeitsstil passt.','Werkstatt'],
['messen-anzeichnen','Messen und Anzeichnen ohne teure Fehler','Bandmaß, Winkel, Wasserwaage und Bleistift korrekt einsetzen – mit praktischer Kontrollroutine.','Handwerk'],
['saegen-vergleich','Handsäge, Stichsäge oder Kreissäge?','Die richtige Säge für Zuschnitt, Kurve und Abbruch – inklusive Sicherheits-Check.','Elektro'],
['dübel-wählen','Dübel passend zur Wand wählen','Gipskarton, Ziegel, Beton oder unbekannter Untergrund: Befestigungen systematisch planen.','Wohnung'],
['sicher-heimwerken','Sicher heimwerken: Schutz, Ordnung, Routine','Augen, Ohren, Atemwege und Hände schützen – mit einfachen Regeln für jede Werkstatt.','Sicherheit'],
['werkzeug-pflegen','Werkzeug pflegen und Rost vermeiden','Reinigung, trockene Lagerung, Schneidenpflege und Akkupflege verlängern die Nutzungsdauer.','Werkstatt'],
['drehmomentschluessel','Drehmomentschlüssel richtig benutzen','Bereich, Einheit, Einstellung und Lagerung: So arbeitest du kontrolliert an Fahrrad und Auto.','Handwerk'],
['leiter-kaufen','Leiter kaufen: Höhe, Stand und Sicherheit','Tritt, Stehleiter oder Anlegeleiter? So wählst du passend zu Raumhöhe und Aufgabe.','Haus'],
['rasenpflege-werkzeug','Werkzeug für einen gepflegten Rasen','Mäher, Trimmer, Rechen und Kantenwerkzeug passend zu Fläche und Gelände auswählen.','Garten'],
['werkzeug-qualitaet-erkennen','Gutes Werkzeug erkennen','Material, Verarbeitung, Ergonomie und Ersatzteile: Qualitätsmerkmale ohne Markenblindheit.','Kaufberatung']
].map((x,i)=>({slug:x[0].normalize('NFD').replace(/[\u0300-\u036f]/g,''),title:x[1],intro:x[2],tag:x[3],time:6+(i%5)}));
let fav=new Set(JSON.parse(localStorage.getItem('wf-favs')||'[]')), shown=8, active='Alle';
const $=s=>document.querySelector(s), esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saveFav(){localStorage.setItem('wf-favs',JSON.stringify([...fav]));document.querySelector('#favTop b').textContent=fav.size}
function productCard(p){return `<article class="product"><img src="${p.img}" alt="${esc(p.name)}" loading="lazy"><div class="productBody"><span class="meta">${p.brand} · ${p.cat} · ${p.use}</span><h3>${esc(p.name)}</h3><p>Produktidentität und Angebot am 12.09.2026 auf Amazon.de geprüft. Verfügbarkeit kann sich ändern.</p><div class="price">${p.price}</div><div class="actions"><a class="button" target="_blank" rel="sponsored noopener" href="https://www.amazon.de/dp/${p.asin}/ref=nosim?tag=${TAG}">Bei Amazon ansehen*</a><button class="heart ${fav.has(p.asin)?'on':''}" data-fav="${p.asin}" aria-label="${esc(p.name)} merken">♥</button></div></div></article>`}
function home(){document.title='Werkzeug Finder – Das richtige Werkzeug für dein Projekt';return `<section class="hero"><div class="heroCopy"><span class="eyebrow">Klar auswählen. Besser arbeiten.</span><h1>Mach’s richtig. Von Anfang an.</h1><p>Ob erste Mietwohnung, eigenes Haus, Garten oder Werkstatt: Finde genau das Werkzeug, das zu deinem Projekt und deinem Können passt.</p><div class="actions"><a class="button accent" href="#finder">Werkzeug finden</a><a class="button ghost" style="color:white" href="#ratgeber">Erst informieren</a></div><div class="stats"><div class="stat"><b>12</b>geprüfte Modelle</div><div class="stat"><b>20</b>Ratgeber</div><div class="stat"><b>0</b>erfundene Bewertungen</div></div></div><div class="heroImage"><span class="caption">Eigene KI-Illustration · keine Produktabbildung</span></div></section>
<section class="section" id="finder"><span class="eyebrow">Dein Werkzeug-Finder</span><h2>Was möchtest du anpacken?</h2><div class="finderPanel"><div class="needs">${['Alle','Wohnung','Haus','Garten','Werkstatt'].map(x=>`<button class="chip ${x===active?'active':''}" data-use="${x}">${x}</button>`).join('')}</div><div class="chips" style="margin-top:12px">${['Alle Produkte','Koffer','Elektro'].map(x=>`<button class="chip" data-cat="${x}">${x}</button>`).join('')}</div><div class="toolbar"><input id="search" type="search" placeholder="Werkzeug oder Marke suchen" aria-label="Produkte durchsuchen"><select id="brand"><option value="">Alle Marken</option>${[...new Set(products.map(p=>p.brand))].map(x=>`<option>${x}</option>`).join('')}</select><select id="sort"><option value="rec">Empfehlung</option><option value="low">Preis aufsteigend</option><option value="high">Preis absteigend</option></select></div><div class="notice"><b>Transparenz:</b> Gewünscht waren 100 Produkte. Mangels authentifizierter Amazon-Produktschnittstelle veröffentlichen wir vorerst 12 am 12.09.2026 manuell geprüfte Angebote. Preise und Verfügbarkeit werden nicht als dauerhaft aktuell ausgegeben.</div><div id="resultCount" class="meta"></div><div class="productGrid" id="produkte"></div><button class="load" id="loadMore">Weitere Produkte anzeigen</button></div></section>
<section class="section" id="beratung"><span class="eyebrow">Kaufberatung ohne Fachchinesisch</span><h2>Erst verstehen. Dann kaufen.</h2><div class="productGrid"><div class="editorial"><span class="meta">Erste Werkstatt</span><h3>Ein guter Arbeitsplatz spart mehr Nerven als das hundertste Spezialwerkzeug.</h3><a href="/ratgeber/werkstatt-einrichten">Werkstatt planen →</a></div><article class="articleCard"><div class="num">01</div><h3>Wohnung</h3><p>Für Möbel, Bilder und kleine Reparaturen kompakt starten.</p><a href="/ratgeber/werkzeug-fuer-mietwohnung">Zur Checkliste →</a></article><article class="articleCard"><div class="num">02</div><h3>Haus</h3><p>Solide Grundausstattung, die mit den Aufgaben wachsen kann.</p><a href="/ratgeber/werkzeug-fuer-haus">Hausausstattung planen →</a></article><article class="articleCard"><div class="num">03</div><h3>Garten</h3><p>Werkzeug nach Fläche, Pflanzen und Lagerplatz auswählen.</p><a href="/ratgeber/gartenwerkzeug-grundausstattung">Garten-Guide öffnen →</a></article></div></section>
<section class="section" id="ratgeber"><span class="eyebrow">Werkzeug-Wissen</span><h2>20 Ratgeber für bessere Projekte.</h2><div class="articleGrid">${topics.map((a,i)=>`<article class="articleCard"><div class="num">${String(i+1).padStart(2,'0')}</div><span class="meta">${a.tag} · ${a.time} Min.</span><h3>${a.title}</h3><p>${a.intro}</p><a href="/ratgeber/${a.slug}">Ratgeber lesen →</a></article>`).join('')}</div></section>
<section class="section legal" id="transparenz"><span class="eyebrow">Transparenz</span><h2>So empfehlen wir.</h2><p>Werkzeug Finder bewertet keine Produkte aus eigener Praxiserfahrung, wenn kein dokumentierter Test vorliegt. Die aktuelle Auswahl basiert auf überprüften Amazon-Produktseiten, klaren Anwendungsfällen, sinnvoller Sortimentsbreite und nachvollziehbaren technischen Merkmalen. Produktbilder, Preise und Verfügbarkeit stammen zum angegebenen Prüfzeitpunkt aus sichtbaren Amazon-Angeboten. Affiliate-Links enthalten ausschließlich die Partner-ID <b>${TAG}</b>.</p></section>`}
function article(a){let related=topics.filter(x=>x.slug!==a.slug).slice(0,2);return `<article class="articlePage"><a href="/#ratgeber">← Alle Ratgeber</a><p class="eyebrow">${a.tag} · ${a.time} Minuten Lesezeit</p><h1>${a.title}</h1><p style="font-size:1.25rem">${a.intro}</p><h2>Worum es bei der Auswahl wirklich geht</h2><p>Das passende Werkzeug ist nicht automatisch das größte oder teuerste. Entscheidend sind Material, Häufigkeit der Nutzung, verfügbarer Platz und die Präzision, die dein Projekt verlangt. Für gelegentliche Arbeiten lohnt sich ein kompaktes, solides Set. Wer regelmäßig arbeitet, ergänzt gezielt und achtet auf Ergonomie, Ersatzteile und ein einheitliches Akkusystem.</p><h2>Ein praktisches Beispiel</h2><p>Angenommen, du möchtest ein Regal montieren: Prüfe zuerst die Wand, bestimme Bohrer und Dübel, miss zweimal und markiere sauber. Lege Schutzbrille, Leitungssucher, Wasserwaage, Bohrmaschine, passenden Bit und Staubsauger bereit. Diese Vorbereitung verhindert die häufigsten Schäden – lange bevor Kraft oder Maschinenleistung wichtig werden.</p><h2>So gehst du Schritt für Schritt vor</h2><p><b>1. Aufgabe eingrenzen:</b> Was soll bearbeitet, verbunden oder gemessen werden? <b>2. Untergrund prüfen:</b> Holz, Metall, Mauerwerk und Gipskarton brauchen unterschiedliche Lösungen. <b>3. Werkzeug passend dimensionieren:</b> Arbeitsbereich und Zubehör müssen zusammenpassen. <b>4. Sicher arbeiten:</b> Anleitung lesen, Arbeitsbereich freihalten und Schutz passend zur Gefahr wählen.</p><div class="checklist"><h2>Checkliste</h2><ul><li>Material und Abmessungen geprüft</li><li>Passendes Werkzeug und Zubehör bereitgelegt</li><li>Strom-, Wasser- oder Gasleitungen ausgeschlossen</li><li>Schutzbrille und erforderlicher Gehörschutz vorhanden</li><li>Werkstück sicher fixiert</li><li>Ergebnis vor dem finalen Schritt kontrolliert</li></ul></div><h2>Häufige Fehler vermeiden</h2><p>Viele Probleme entstehen durch falsche Größe, stumpfes Zubehör oder zu viel Kraft. Stoppe, wenn ein Werkzeug verkantet, ungewöhnlich heiß wird oder der Untergrund unerwartet reagiert. Im Zweifel ist eine kurze Materialprobe an einer unauffälligen Stelle sinnvoller als ein riskanter Versuch.</p><h2>Quellen und weiterführende Hinweise</h2><p>Für sicherheitsrelevante Arbeiten gelten die Anleitung des Herstellers, die Hinweise der Deutschen Gesetzlichen Unfallversicherung und bei Elektroinstallationen die Regeln des zuständigen Fachhandwerks. Arbeiten an festen Elektro-, Gas- oder Wasserinstallationen gehören je nach Umfang in Fachhände.</p><div class="related">${related.map(x=>`<a class="articleCard" href="/ratgeber/${x.slug}"><span class="meta">Weiterlesen</span><h3>${x.title}</h3><p>${x.intro}</p></a>`).join('')}</div><div class="notice">Ausgewählte Startsets findest du im <a href="/#produkte"><b>Produktfinder</b></a>. Produktlinks sind Werbelinks zu Amazon.</div></article>`}
function legal(kind){return `<section class="section legal"><span class="eyebrow">Rechtliches</span><h2>${kind}</h2><div class="notice"><b>Noch nicht veröffentlichungsreif:</b> Betreibername, ladungsfähige Anschrift, Kontaktangaben und gegebenenfalls Umsatzsteuer-ID wurden nicht angegeben. Diese Pflichtangaben werden nicht erfunden und müssen vor öffentlicher Bewerbung ergänzt werden.</div><p>Bitte übermittle die vollständigen Betreiberangaben. Für die Datenschutzerklärung werden außerdem die tatsächlich aktivierten Dienste, Hosting-Verträge und die serverseitige Amazon-API-Konfiguration benötigt.</p></section>`}
function render(){let path=decodeURI(location.pathname);let a=path.startsWith('/ratgeber/')?topics.find(x=>'/ratgeber/'+x.slug===path):null;$('#main').innerHTML=a?article(a):path==='/impressum'?legal('Impressum'):path==='/datenschutz'?legal('Datenschutz'):home();bind();saveFav();scrollTo(0,0)}
function bind(){if(!$('#produkte'))return;let cat='Alle Produkte';function update(){let q=($('#search').value||'').toLowerCase(),brand=$('#brand').value;let arr=products.filter(p=>(active==='Alle'||p.use===active)&&(cat==='Alle Produkte'||p.cat===cat)&&(!brand||p.brand===brand)&&(p.name+' '+p.brand).toLowerCase().includes(q));let sort=$('#sort').value;if(sort!=='rec')arr.sort((a,b)=>(parseFloat(a.price.replace(',','.'))-parseFloat(b.price.replace(',','.')))*(sort==='low'?1:-1));$('#resultCount').textContent=`${arr.length} geprüfte Modelle`;$('#produkte').innerHTML=arr.slice(0,shown).map(productCard).join('')+(arr.length===0?'<p>Keine passenden Produkte gefunden.</p>':'');$('#loadMore').hidden=shown>=arr.length;document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{fav.has(b.dataset.fav)?fav.delete(b.dataset.fav):fav.add(b.dataset.fav);saveFav();update()})}document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{active=b.dataset.use;document.querySelectorAll('[data-use]').forEach(x=>x.classList.toggle('active',x.dataset.use===active));update()});document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;document.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x.dataset.cat===cat));update()});['search','brand','sort'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',update));$('#loadMore').onclick=()=>{shown=99;update()};update()}
$('#menu').onclick=()=>{let n=document.querySelector('nav'),open=n.style.display!=='flex';n.style.cssText=open?'display:flex;position:absolute;top:76px;left:0;right:0;background:#f5f3ed;padding:22px;flex-direction:column;border-bottom:1px solid #ddd9cf':' ';$('#menu').setAttribute('aria-expanded',open)};document.addEventListener('click',e=>{let a=e.target.closest('a');if(a&&a.origin===location.origin){e.preventDefault();history.pushState({},'',a.pathname+a.hash);document.querySelector('nav').style.cssText='';render();if(a.hash)setTimeout(()=>document.querySelector(a.hash)?.scrollIntoView(),0)}});addEventListener('popstate',render);render();
